"""Alembic environment — async SQLite, PHANTOM OS backend.

Two entry modes:

* **Programmatic** (the only mode used at runtime): db/database.py opens a
  connection on the app's own async engine and injects the *sync* connection
  via ``config.attributes["connection"]`` (the documented recipe for running
  Alembic under an async engine). Logging is NOT reconfigured in this mode —
  the app owns logging.
* **CLI** (developer workflow): ``alembic revision --autogenerate`` /
  ``alembic upgrade head`` from ``src/backend``. Builds its own throwaway
  async engine from ``config.database_url``.
"""
from __future__ import annotations

import asyncio
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# db/alembic/env.py → backend root; needed so `config`/`db` import under CLI.
_BACKEND_ROOT = Path(__file__).resolve().parents[2]
if str(_BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(_BACKEND_ROOT))

from config import config as phantom_config  # noqa: E402
from db.database import Base  # noqa: E402
from db import models, tom_models  # noqa: E402,F401 — registers all tables on Base

config = context.config

# Only touch logging when running standalone from the CLI ini file —
# reconfiguring logging from inside the live backend would clobber the
# app's handlers.
if config.attributes.get("connection") is None and config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The ini URL is a placeholder; the app config owns the real location.
config.set_main_option("sqlalchemy.url", phantom_config.database_url)

target_metadata = Base.metadata


def _configure_and_run(connection: Connection) -> None:
    # batch-режим перебудовує таблицю через DROP старої. SQLite з увімкненими
    # FK робить при DROP неявний DELETE FROM — і ON DELETE CASCADE зносить усі
    # дочірні рядки. Саме так міграція курсора читання стерла всі повідомлення
    # месенджера. На час міграцій FK вимикаємо, як і радить Alembic.
    connection.exec_driver_sql("PRAGMA foreign_keys=OFF")
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # SQLite can't ALTER most things in place — batch mode rebuilds
        # tables behind the scenes so autogenerated ALTERs actually apply.
        render_as_batch=True,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_offline() -> None:
    """Offline (--sql) mode: emit DDL without a DB connection."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def _run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(_configure_and_run)
    await connectable.dispose()


def run_migrations_online() -> None:
    injected = config.attributes.get("connection")
    if injected is not None:
        # Programmatic path: the backend passed us a live sync connection
        # (via AsyncConnection.run_sync). No engine of our own.
        _configure_and_run(injected)
    else:
        # CLI path: build a private async engine.
        asyncio.run(_run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
