"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-07-20 20:27:08.521895

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_chat_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_chat_threads', schema=None) as batch_op:
        batch_op.create_index('ix_agent_chat_threads_task', ['task_id'], unique=False)
        batch_op.create_index('ix_agent_chat_threads_task_created', ['task_id', 'created_at'], unique=False)

    op.create_table('agent_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('standing_orders', sa.Text(), nullable=False),
    sa.Column('system_prompt_extension', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_tool_use_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('step_idx', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_kind', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_after_s', sa.Float(), nullable=True),
    sa.Column('fell_through_to_fallback', sa.Boolean(), nullable=False),
    sa.Column('cooling_triggered', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_excerpt', sa.Text(), nullable=True),
    sa.Column('response_excerpt', sa.Text(), nullable=True),
    sa.Column('prompt_sections', sa.String(length=256), nullable=True),
    sa.Column('tool_args_json', sa.Text(), nullable=True),
    sa.Column('tool_result_summary', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_tool_use_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_tool_use_log_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tool_use_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tool_use_log_user_id'), ['user_id'], unique=False)

    op.create_table('alarms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('time_str', sa.String(length=5), nullable=False),
    sa.Column('repeat', sa.String(length=16), nullable=False),
    sa.Column('next_trigger', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beliefs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=16), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('predicate_key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('belief_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('log_odds', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('embedding_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('last_confirmed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['superseded_by'], ['beliefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beliefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beliefs_predicate_key'), ['predicate_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_beliefs_status'), ['status'], unique=False)

    op.create_table('calendar_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('inputs_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('triggered_by', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_agent_runs', schema=None) as batch_op:
        batch_op.create_index('ix_custom_agent_runs_agent', ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_agent_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_custom_agent_runs_task', ['task_id'], unique=False)

    op.create_table('custom_agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('goal_template', sa.Text(), nullable=False),
    sa.Column('inputs_schema_json', sa.Text(), nullable=False),
    sa.Column('cards_json', sa.Text(), nullable=False),
    sa.Column('links_json', sa.Text(), nullable=False),
    sa.Column('recipients_json', sa.Text(), nullable=False),
    sa.Column('schedule_json', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_agents_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_custom_agents_owner', ['owner_user_id'], unique=False)

    op.create_table('dream_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.Float(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('batch_lo', sa.Integer(), nullable=False),
    sa.Column('batch_hi', sa.Integer(), nullable=False),
    sa.Column('heartbeat', sa.Float(), nullable=False),
    sa.Column('committed_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('current_level', sa.Float(), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=False),
    sa.Column('decay_rate', sa.Float(), nullable=False),
    sa.Column('pressure_rate', sa.Float(), nullable=False),
    sa.Column('last_satisfied_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(length=36), nullable=True),
    sa.Column('prosody', sa.Text(), nullable=True),
    sa.Column('context_snap', sa.Text(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.Float(), nullable=True),
    sa.Column('dream_processed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodes_dream_processed'), ['dream_processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_session_id'), ['session_id'], unique=False)

    op.create_table('epochs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('topic_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('epochs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_epochs_status'), ['status'], unique=False)

    op.create_table('ghost_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_path', sa.String(length=512), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managed_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('key_hint', sa.String(length=12), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('cooldown_until', sa.Float(), nullable=True),
    sa.Column('requests_total', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('failures_total', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('managed_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managed_keys_provider'), ['provider'], unique=False)
        batch_op.create_index('ix_managed_keys_provider_prio', ['provider', 'priority'], unique=False)

    op.create_table('mobile_approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('action_name', sa.String(length=64), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('nonce_b64', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=True),
    sa.Column('signature_b64', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mobile_approval_requests', schema=None) as batch_op:
        batch_op.create_index('ix_mobile_approval_pending', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mobile_approval_requests_task_id'), ['task_id'], unique=False)

    op.create_table('phantom_mind_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phantom_mind_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phantom_mind_state_user_id'), ['user_id'], unique=True)

    op.create_table('phantom_narrative',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('narrative_text', sa.Text(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phantom_narrative', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phantom_narrative_user_id'), ['user_id'], unique=True)

    op.create_table('polis_citizens',
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('successes', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('revisions', sa.Integer(), nullable=False),
    sa.Column('tokens_produced', sa.Integer(), nullable=False),
    sa.Column('domains_json', sa.Text(), nullable=False),
    sa.Column('recent_titles_json', sa.Text(), nullable=False),
    sa.Column('last_active', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('reflection_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('consumed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reflection_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reflection_queue_consumed'), ['consumed'], unique=False)
        batch_op.create_index(batch_op.f('ix_reflection_queue_priority'), ['priority'], unique=False)

    op.create_table('semantic_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('topic_key', sa.String(length=64), nullable=True),
    sa.Column('embedding_id', sa.String(length=36), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('decay_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('last_accessed', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('radar_present', sa.Boolean(), nullable=True),
    sa.Column('radar_motion_energy', sa.Integer(), nullable=True),
    sa.Column('radar_static_energy', sa.Integer(), nullable=True),
    sa.Column('radar_distance_cm', sa.Integer(), nullable=True),
    sa.Column('radar_breath_bpm', sa.Float(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.Column('gps_fix', sa.Boolean(), nullable=True),
    sa.Column('gps_speed_kmh', sa.Float(), nullable=True),
    sa.Column('env_temp_c', sa.Float(), nullable=True),
    sa.Column('env_pressure_hpa', sa.Float(), nullable=True),
    sa.Column('env_aqi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('state_transitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_state', sa.String(length=16), nullable=False),
    sa.Column('to_state', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('parent_task_id', sa.String(length=36), nullable=True),
    sa.Column('sender', sa.String(length=64), nullable=False),
    sa.Column('receiver', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('media_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_team_chat_messages_task', ['task_id'], unique=False)
        batch_op.create_index('ix_team_chat_messages_task_created', ['task_id', 'created_at'], unique=False)

    op.create_table('timers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('fired', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('rfid_uid_hash', sa.String(length=128), nullable=True),
    sa.Column('pin_hash', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('preferences_json', sa.Text(), nullable=False),
    sa.Column('behavioral_model_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wardriving_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('ssid', sa.String(length=256), nullable=False),
    sa.Column('rssi', sa.Integer(), nullable=False),
    sa.Column('encryption', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat_rounded', sa.Float(), nullable=False),
    sa.Column('lon_rounded', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac', 'lat_rounded', 'lon_rounded')
    )
    op.create_table('agent_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('step_idx', sa.Integer(), nullable=False),
    sa.Column('sub_goal_id', sa.String(length=36), nullable=True),
    sa.Column('action_name', sa.String(length=64), nullable=False),
    sa.Column('args_json', sa.Text(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('monologue_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('retried_from', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_audit_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_audit_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_agent_audit_user', ['user_id'], unique=False)

    op.create_table('agent_checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_checkpoints_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_agent_checkpoints_user', ['user_id'], unique=False)

    op.create_table('agent_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('audit_entry_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_feedback_audit_entry_id'), ['audit_entry_id'], unique=False)
        batch_op.create_index('ix_agent_feedback_user', ['user_id'], unique=False)

    op.create_table('agent_memory_seeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_actions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_memory_seeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_memory_seeds_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_agent_memory_seeds_user', ['user_id'], unique=False)

    op.create_table('agent_missions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('success_criteria', sa.Text(), nullable=False),
    sa.Column('quality_bar', sa.Text(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('budget_constraints_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('ledger_path', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_missions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_agent_missions_user_status', ['user_id', 'status'], unique=False)

    op.create_table('agent_relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_role_id', sa.String(length=36), nullable=False),
    sa.Column('target_role_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('trust_level', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_role_id'], ['agent_roles.id'], ),
    sa.ForeignKeyConstraint(['target_role_id'], ['agent_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('track', sa.String(length=16), nullable=False),
    sa.Column('sub_goals_json', sa.Text(), nullable=True),
    sa.Column('observations_json', sa.Text(), nullable=True),
    sa.Column('self_model_json', sa.Text(), nullable=True),
    sa.Column('thought_budget_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('paused_reason', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('runtime_snapshot_json', sa.Text(), nullable=True),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tasks_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index('ix_agent_tasks_user', ['user_id'], unique=False)

    op.create_table('belief_evidence',
    sa.Column('belief_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('polarity', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('added_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['belief_id'], ['beliefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('belief_id', 'source_type', 'source_id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('state_history_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contradictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('belief_a', sa.Integer(), nullable=False),
    sa.Column('belief_b', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.Float(), nullable=False),
    sa.Column('resolved_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['belief_a'], ['beliefs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['belief_b'], ['beliefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contradictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contradictions_status'), ['status'], unique=False)

    op.create_table('core_narrative_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_narrative_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_narrative_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_narrative_log_user_id'), ['user_id'], unique=False)

    op.create_table('curiosity_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curiosity_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curiosity_queue_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_curiosity_queue_user_id'), ['user_id'], unique=False)

    op.create_table('dream_mutations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('op', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('precond', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['dream_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals_persistent',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('horizon_level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_agent', sa.String(length=64), nullable=False),
    sa.Column('kpi', sa.String(length=256), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('blockers_json', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('value_alignment', sa.Float(), nullable=False),
    sa.Column('drive_pull', sa.Float(), nullable=False),
    sa.Column('urgency', sa.Float(), nullable=False),
    sa.Column('tractability', sa.Float(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['goals_persistent.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals_persistent', schema=None) as batch_op:
        batch_op.create_index('ix_goals_horizon', ['horizon_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_persistent_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_persistent_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_goals_status', ['status'], unique=False)

    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('belief_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('test_mode', sa.String(length=16), nullable=False),
    sa.Column('probe_hint', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('resolved_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['belief_id'], ['beliefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hypotheses_status'), ['status'], unique=False)

    op.create_table('location_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('place_name', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('city', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_history_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_history_user_id'), ['user_id'], unique=False)

    op.create_table('map_geofences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('geometry_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('on_enter_json', sa.Text(), nullable=False),
    sa.Column('on_exit_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('map_geofences', schema=None) as batch_op:
        batch_op.create_index('ix_map_geofences_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_map_geofences_user_id'), ['user_id'], unique=False)

    op.create_table('map_pois',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_trajectory_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('schedule_json', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('map_trajectory_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_trajectory_patterns_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_map_trajectory_user_label', ['user_id', 'label'], unique=False)

    op.create_table('memory_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('layer', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('embedding_id', sa.String(length=64), nullable=True),
    sa.Column('source_session_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('is_sealed', sa.Boolean(), nullable=False),
    sa.Column('decay_factor', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.Column('entity_slot', sa.String(length=64), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('place_name', sa.String(length=256), nullable=True),
    sa.Column('place_lat', sa.Float(), nullable=True),
    sa.Column('place_lon', sa.Float(), nullable=True),
    sa.Column('place_source', sa.String(length=32), nullable=True),
    sa.Column('place_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_facts', schema=None) as batch_op:
        batch_op.create_index('ix_memory_facts_user_geo', ['user_id', 'place_lat', 'place_lon'], unique=False)

    op.create_table('polis_missions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('pipeline', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('graph_json', sa.Text(), nullable=False),
    sa.Column('chat_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('polis_missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_polis_missions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_polis_missions_user_status', ['user_id', 'status'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('avatar_uri', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('behavioral_model_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'display_name', name='uq_profiles_user_display_name')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index('ix_profiles_user', ['user_id'], unique=False)

    op.create_table('semantic_source',
    sa.Column('semantic_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semantic_id'], ['semantic_memory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('semantic_id', 'episode_id')
    )
    op.create_table('standing_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('schedule_json', sa.Text(), nullable=False),
    sa.Column('action_json', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('fire_count', sa.Integer(), nullable=False),
    sa.Column('last_outcome', sa.Text(), nullable=True),
    sa.Column('in_flight_task_id', sa.String(length=36), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('action_kind', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standing_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standing_orders_action_kind'), ['action_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_standing_orders_in_flight_task_id'), ['in_flight_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_standing_orders_user_id'), ['user_id'], unique=False)

    op.create_table('temporal_anchors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('place_name', sa.String(length=256), nullable=True),
    sa.Column('activity_summary', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('mood', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('exclude_from_prompts', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_facts', schema=None) as batch_op:
        batch_op.create_index('ix_user_facts_user_category', ['user_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_facts_user_id'), ['user_id'], unique=False)

    op.create_table('vault_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vault_audit', schema=None) as batch_op:
        batch_op.create_index('ix_vault_audit_card', ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vault_audit_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_vault_audit_user_action', ['user_id', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_vault_audit_user_id'), ['user_id'], unique=False)

    op.create_table('vault_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('ai_writable', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vault_cards', schema=None) as batch_op:
        batch_op.create_index('ix_vault_cards_active', ['owner_user_id', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vault_cards_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_vault_cards_owner_kind', ['owner_user_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_vault_cards_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('will_budget_ledger',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ledger_date', sa.String(length=10), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ledger_date')
    )
    op.create_table('will_journal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('decision_json', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('budget_delta_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('will_journal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_will_journal_user_id'), ['user_id'], unique=False)

    op.create_table('agent_phases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('success_criteria', sa.Text(), nullable=False),
    sa.Column('expected_duration_h', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('artifacts_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['agent_missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'idx', name='uq_agent_phases_mission_idx')
    )
    with op.batch_alter_table('agent_phases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_phases_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index('ix_agent_phases_mission_idx', ['mission_id', 'idx'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('response_form', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('attachments_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('speaker_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['speaker_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_speaker_user_id'), ['speaker_user_id'], unique=False)

    op.create_table('paired_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('device_name', sa.String(length=128), nullable=False),
    sa.Column('device_model', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('platform_version', sa.String(length=32), nullable=True),
    sa.Column('device_pub_ed25519', sa.String(length=128), nullable=False),
    sa.Column('paired_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.String(length=36), nullable=True),
    sa.Column('revoked_reason', sa.String(length=256), nullable=True),
    sa.Column('capabilities_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paired_devices', schema=None) as batch_op:
        batch_op.create_index('ix_paired_devices_active', ['user_id', 'revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_paired_devices_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index('ix_paired_devices_user', ['user_id'], unique=False)

    op.create_table('mobile_sensor_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('device_ts_ms', sa.Integer(), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.Column('gps_accuracy_m', sa.Float(), nullable=True),
    sa.Column('motion_class', sa.String(length=24), nullable=True),
    sa.Column('mic_rms', sa.Float(), nullable=True),
    sa.Column('body_bpm', sa.Float(), nullable=True),
    sa.Column('body_hrv', sa.Float(), nullable=True),
    sa.Column('ble_json', sa.Text(), nullable=False),
    sa.Column('wifi_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['paired_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mobile_sensor_batches', schema=None) as batch_op:
        batch_op.create_index('ix_mobile_sensor_batches_device_ts', ['device_id', 'received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mobile_sensor_batches_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobile_sensor_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mobile_sensor_batches_user_id'))
        batch_op.drop_index('ix_mobile_sensor_batches_device_ts')

    op.drop_table('mobile_sensor_batches')
    with op.batch_alter_table('paired_devices', schema=None) as batch_op:
        batch_op.drop_index('ix_paired_devices_user')
        batch_op.drop_index(batch_op.f('ix_paired_devices_profile_id'))
        batch_op.drop_index('ix_paired_devices_active')

    op.drop_table('paired_devices')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_speaker_user_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('agent_phases', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_phases_mission_idx')
        batch_op.drop_index(batch_op.f('ix_agent_phases_mission_id'))

    op.drop_table('agent_phases')
    with op.batch_alter_table('will_journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_will_journal_user_id'))

    op.drop_table('will_journal')
    op.drop_table('will_budget_ledger')
    with op.batch_alter_table('vault_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_cards_owner_user_id'))
        batch_op.drop_index('ix_vault_cards_owner_kind')
        batch_op.drop_index(batch_op.f('ix_vault_cards_deleted_at'))
        batch_op.drop_index('ix_vault_cards_active')

    op.drop_table('vault_cards')
    with op.batch_alter_table('vault_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_audit_user_id'))
        batch_op.drop_index('ix_vault_audit_user_action')
        batch_op.drop_index(batch_op.f('ix_vault_audit_created_at'))
        batch_op.drop_index('ix_vault_audit_card')

    op.drop_table('vault_audit')
    with op.batch_alter_table('user_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_facts_user_id'))
        batch_op.drop_index('ix_user_facts_user_category')

    op.drop_table('user_facts')
    op.drop_table('temporal_anchors')
    with op.batch_alter_table('standing_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standing_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_standing_orders_in_flight_task_id'))
        batch_op.drop_index(batch_op.f('ix_standing_orders_action_kind'))

    op.drop_table('standing_orders')
    op.drop_table('semantic_source')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_profiles_user')

    op.drop_table('profiles')
    with op.batch_alter_table('polis_missions', schema=None) as batch_op:
        batch_op.drop_index('ix_polis_missions_user_status')
        batch_op.drop_index(batch_op.f('ix_polis_missions_user_id'))

    op.drop_table('polis_missions')
    with op.batch_alter_table('memory_facts', schema=None) as batch_op:
        batch_op.drop_index('ix_memory_facts_user_geo')

    op.drop_table('memory_facts')
    with op.batch_alter_table('map_trajectory_patterns', schema=None) as batch_op:
        batch_op.drop_index('ix_map_trajectory_user_label')
        batch_op.drop_index(batch_op.f('ix_map_trajectory_patterns_user_id'))

    op.drop_table('map_trajectory_patterns')
    op.drop_table('map_pois')
    with op.batch_alter_table('map_geofences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_geofences_user_id'))
        batch_op.drop_index('ix_map_geofences_user_active')

    op.drop_table('map_geofences')
    with op.batch_alter_table('location_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_location_history_timestamp'))

    op.drop_table('location_history')
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hypotheses_status'))

    op.drop_table('hypotheses')
    with op.batch_alter_table('goals_persistent', schema=None) as batch_op:
        batch_op.drop_index('ix_goals_status')
        batch_op.drop_index(batch_op.f('ix_goals_persistent_user_id'))
        batch_op.drop_index(batch_op.f('ix_goals_persistent_created_at'))
        batch_op.drop_index('ix_goals_horizon')

    op.drop_table('goals_persistent')
    op.drop_table('dream_mutations')
    with op.batch_alter_table('curiosity_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curiosity_queue_user_id'))
        batch_op.drop_index(batch_op.f('ix_curiosity_queue_created_at'))

    op.drop_table('curiosity_queue')
    with op.batch_alter_table('core_narrative_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_narrative_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_core_narrative_log_created_at'))

    op.drop_table('core_narrative_log')
    with op.batch_alter_table('contradictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contradictions_status'))

    op.drop_table('contradictions')
    op.drop_table('chat_sessions')
    op.drop_table('belief_evidence')
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_tasks_user')
        batch_op.drop_index(batch_op.f('ix_agent_tasks_mission_id'))
        batch_op.drop_index(batch_op.f('ix_agent_tasks_created_at'))

    op.drop_table('agent_tasks')
    op.drop_table('agent_relations')
    with op.batch_alter_table('agent_missions', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_missions_user_status')
        batch_op.drop_index(batch_op.f('ix_agent_missions_user_id'))

    op.drop_table('agent_missions')
    with op.batch_alter_table('agent_memory_seeds', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_memory_seeds_user')
        batch_op.drop_index(batch_op.f('ix_agent_memory_seeds_created_at'))

    op.drop_table('agent_memory_seeds')
    with op.batch_alter_table('agent_feedback', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_feedback_user')
        batch_op.drop_index(batch_op.f('ix_agent_feedback_audit_entry_id'))

    op.drop_table('agent_feedback')
    with op.batch_alter_table('agent_checkpoints', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_checkpoints_user')
        batch_op.drop_index(batch_op.f('ix_agent_checkpoints_task_id'))

    op.drop_table('agent_checkpoints')
    with op.batch_alter_table('agent_audit', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_audit_user')
        batch_op.drop_index(batch_op.f('ix_agent_audit_timestamp'))
        batch_op.drop_index(batch_op.f('ix_agent_audit_task_id'))

    op.drop_table('agent_audit')
    op.drop_table('wardriving_records')
    op.drop_table('users')
    op.drop_table('timers')
    with op.batch_alter_table('team_chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_team_chat_messages_task_created')
        batch_op.drop_index('ix_team_chat_messages_task')

    op.drop_table('team_chat_messages')
    op.drop_table('state_transitions')
    op.drop_table('settings')
    with op.batch_alter_table('sensor_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_logs_timestamp'))

    op.drop_table('sensor_logs')
    op.drop_table('semantic_memory')
    with op.batch_alter_table('reflection_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reflection_queue_priority'))
        batch_op.drop_index(batch_op.f('ix_reflection_queue_consumed'))

    op.drop_table('reflection_queue')
    op.drop_table('polis_citizens')
    with op.batch_alter_table('phantom_narrative', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phantom_narrative_user_id'))

    op.drop_table('phantom_narrative')
    with op.batch_alter_table('phantom_mind_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phantom_mind_state_user_id'))

    op.drop_table('phantom_mind_state')
    with op.batch_alter_table('mobile_approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mobile_approval_requests_task_id'))
        batch_op.drop_index('ix_mobile_approval_pending')

    op.drop_table('mobile_approval_requests')
    with op.batch_alter_table('managed_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_managed_keys_provider_prio')
        batch_op.drop_index(batch_op.f('ix_managed_keys_provider'))

    op.drop_table('managed_keys')
    op.drop_table('ghost_records')
    with op.batch_alter_table('epochs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epochs_status'))

    op.drop_table('epochs')
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_session_id'))
        batch_op.drop_index(batch_op.f('ix_episodes_dream_processed'))

    op.drop_table('episodes')
    op.drop_table('drive_state')
    op.drop_table('dream_jobs')
    with op.batch_alter_table('custom_agents', schema=None) as batch_op:
        batch_op.drop_index('ix_custom_agents_owner')
        batch_op.drop_index(batch_op.f('ix_custom_agents_created_at'))

    op.drop_table('custom_agents')
    with op.batch_alter_table('custom_agent_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_custom_agent_runs_task')
        batch_op.drop_index(batch_op.f('ix_custom_agent_runs_created_at'))
        batch_op.drop_index('ix_custom_agent_runs_agent')

    op.drop_table('custom_agent_runs')
    op.drop_table('calendar_events')
    with op.batch_alter_table('beliefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beliefs_status'))
        batch_op.drop_index(batch_op.f('ix_beliefs_predicate_key'))

    op.drop_table('beliefs')
    op.drop_table('alarms')
    with op.batch_alter_table('ai_tool_use_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_tool_use_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_tool_use_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_ai_tool_use_log_task_id'))

    op.drop_table('ai_tool_use_log')
    op.drop_table('agent_roles')
    with op.batch_alter_table('agent_chat_threads', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_chat_threads_task_created')
        batch_op.drop_index('ix_agent_chat_threads_task')

    op.drop_table('agent_chat_threads')
    # ### end Alembic commands ###
