"""add slug to tenantorg

Revision ID: 2126616c8ce4
Revises: 60e0d820bcc2
Create Date: 2026-07-29 14:18:36.592261

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2126616c8ce4'
down_revision: Union[str, None] = '60e0d820bcc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_tenants_slug', ['slug'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tenants_slug', type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
